{% set name = "cmake_format" %}
{% set version = "0.6.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: fd6e95c6f4f44fe7eb24cda118ba7e3e1a61997c24127ab5e7ca414940e07e5a

build:
  number: 0
  noarch: python
  entry_points:
    - cmake-format=cmake_format.__main__:main
    - cmake-annotate=cmake_format.annotate:main
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six

test:
  imports:
    - cmake_format
    - cmake_format.command_tests
    - cmake_format.parse_funs
  commands:
    - cmake-format --help
    - cmake-annotate --help

about:
  home: https://github.com/cheshirekow/cmake_format
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Can format your listfiles so they don't look like crap

extra:
  recipe-maintainers:
    - xhochy
