travis:
  secure:
    BINSTAR_TOKEN: IrYTN+YCRHYjaEmpeTVezLBxD+Jb6g/SsUeSVB9Sz/WpMD+vpGdNwOBw0AMykatzYVvf5AljdrD59F02hUZ1tPA+dKrOZR8cXgqpeFDuSHjhYWAf8RBevMhH9vXj/ZBRCyb7m9UP0gRtICyFJxOEXMntzpTLXXAe+CFGXrNrqn4793axaPnp2zzvZiSby+WvtNOHxTs2c5O75ItI4AUy0icy+Oih75FczZ5OIsbmtRqUg9zns2L2wkiBRzKweLadCB4URMBJZ7NkWg03d3x8hRo+axmoVxMckA5BkIYUdF3zjE60jAEX4Xi+jaTNcDDozNtWiaScMNhwj5B1qfoXfJjdkVg1hSS7KBrp/zF0yXXtNQum+Wzf9UlBRjNiJ71rXg1rcLJk31gbM60ttSscKl7AEmIGjLl+st4IoItyDpKN5YVeJrvzV/SeeT/wXf+tHxC5WMNyTWyoHwuFHk3s93MFYomZB+EZpvaMKuCI2Vm64s6JmshRO6D3tVje4BPZ/CzIbhyztDHINlA02yH3QeT6Fj5iM8K3br+QZTUOcMa7GZQ0odKDYV05C0GXQdmWeuy6PeKgJm9XhnAGsafN3p3Z4lTMDJrY73b2bpe1ON8Tp7F4zhOcNCj7MnOtWmRnNbAREZMQb/IEqvliqGskJ/yYBwuXerav57zqJK2sz6A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
